
import type { Article } from './types';

export const articles: Article[] = [
  {
    id: '1',
    slug: 'townsquare-times-your-daily-dose-of-local',
    title: 'Townsquare Times: Your Daily Dose of Local',
    author: 'Alex Doe',
    date: 'October 26, 2023',
    image: 'https://placehold.co/600x400.png',
    category: 'Community',
    excerpt: 'The latest happenings and stories from around our town, keeping you connected to the heart of the community.',
    content: `Welcome to the Townsquare Times, your number one source for all things local. In today's edition, we're covering the annual town festival, a new initiative from the local library, and an interview with the high school's championship-winning soccer team. We believe in the power of local stories to bring people together and foster a stronger sense of community.\n\nFrom city council meetings to profiles of neighborhood heroes, we are dedicated to providing in-depth coverage of the issues and events that matter most to you. Our team of journalists lives right here in town, and we're committed to telling the stories of our shared home with accuracy, passion, and integrity. Thank you for reading, and for being a part of what makes our town so special.`,
    featured: true,
  },
  {
    id: '2',
    slug: 'culinary-renaissance-in-the-downtown-core',
    title: 'A Culinary Renaissance in the Downtown Core',
    author: 'John Smith',
    date: 'October 25, 2023',
    image: 'https://placehold.co/600x400.png',
    category: 'Food & Culture',
    excerpt: 'Discover the new wave of restaurants and chefs that are putting our city back on the culinary map.',
    content: `Once a culinary desert, the city's downtown core is now experiencing a vibrant renaissance. A new generation of chefs, inspired by local ingredients and global flavors, are opening innovative eateries that are drawing foodies from far and wide.\n\nThis piece takes you on a tour of the most exciting new restaurants, from farm-to-table bistros to avant-garde tasting menus. We'll speak with the creative minds behind these establishments to understand their philosophy and what drives them to push culinary boundaries. It's a story of passion, community, and the delicious revival of a neighborhood.`,
    videoUrl: 'https://example.com/video.mp4',
  },
  {
    id: '3',
    slug: 'the-art-of-public-spaces',
    title: 'The Art of Public Spaces: More Than Just Parks',
    author: 'Emily White',
    date: 'October 24, 2023',
    image: 'https://placehold.co/600x400.png',
    category: 'Urban Design',
    excerpt: 'How thoughtful design of public squares, parks, and plazas can foster community and well-being.',
    content: `Public spaces are the heart of a city, the common ground where people from all walks of life can interact. But what makes a public space truly great? It's more than just green grass or a few benches. Effective urban design considers accessibility, programming, aesthetics, and safety to create environments that are both beautiful and functional.\n\nWe explore several successful public space projects, analyzing how they were conceived and the impact they've had on their surrounding communities. From pop-up installations to large-scale park redesigns, discover how cities are investing in their shared spaces to build a more connected and resilient future.`,
  },
  {
    id: '4',
    slug: 'navigating-the-new-economy',
    title: 'Navigating the New Economy: Skills for the Future',
    author: 'Michael Brown',
    date: 'October 23, 2023',
    image: 'https://placehold.co/600x400.png',
    category: 'Business',
    excerpt: 'The job market is changing rapidly. Are you prepared with the skills needed to thrive in the 21st century?',
    content: `Automation, AI, and the gig economy are fundamentally altering the nature of work. The skills that were valuable a decade ago may soon be obsolete. So, what does it take to succeed in this new landscape?\n\nThis article breaks down the essential skills for the future, including digital literacy, critical thinking, creativity, and emotional intelligence. We talk to economists, educators, and business leaders to get their insights on how individuals and organizations can adapt to the changing demands of the modern workforce.`,
  },
    {
    id: '5',
    slug: 'local-music-scene-strikes-a-new-chord',
    title: 'Local Music Scene Strikes a New Chord',
    author: 'Sarah Green',
    date: 'October 22, 2023',
    image: 'https://placehold.co/600x400.png',
    category: 'Music',
    excerpt: 'From indie rock to electronic beats, a new wave of artists is making noise and redefining the city’s sound.',
    content: `In basements, small clubs, and community halls across the city, a musical revolution is brewing. Independent artists are leveraging new technologies and a collaborative spirit to create and distribute their music, bypassing traditional gatekeepers.\n\nWe profile some of the most promising acts in the local scene, exploring their influences, their creative process, and their vision for the future of music in our city. It's a testament to the power of grassroots movements and the enduring appeal of authentic, locally-grown art.`,
    videoUrl: 'https://example.com/video.mp4',
  },
  {
    id: '6',
    slug: 'pandas-in-chengdu',
    title: 'Pandas in Chengdu melt hearts of visitors from around the globe',
    author: 'Travel Correspondent',
    date: '5 hours ago',
    image: 'https://placehold.co/300x300.png',
    category: 'Food & Culture',
    excerpt: 'Ever wonder why giant pandas capture hearts all around the world? We visited the Chengdu Panda Base to find out.',
    content: 'Ever wonder why giant pandas capture hearts all around the world? We visited the Chengdu Panda Base to find out what makes these cuddly creatures so beloved.',
    videoUrl: 'https://example.com/video.mp4',
  },
  {
    id: '7',
    slug: 'exploring-history-at-museums',
    title: 'Exploring history at museums becomes summer trend in China',
    author: 'China Daily',
    date: '6 hours ago',
    image: 'https://placehold.co/300x300.png',
    category: 'Food & Culture',
    excerpt: 'Exploring history at museums becomes summer trend in China. A growing number of young people are choosing to spend their leisure time in museums, learning about the nation\'s rich history and culture.',
    content: 'Exploring history at museums becomes summer trend in China. A growing number of young people are choosing to spend their leisure time in museums, learning about the nation\'s rich history and culture.',
  },
  {
    id: '8',
    slug: 'clues-to-a-forgotten-kingdom',
    title: 'Clues to a forgotten kingdom: Mysteries of Sanxingdui',
    author: 'Trending Weekly',
    date: '22 hours ago',
    image: 'https://placehold.co/300x300.png',
    category: 'Food & Culture',
    excerpt: "Sanxingdui, located in Guanghan, Southwest China's Sichuan Province, was the capital of the ancient Shu Kingdom.",
    content: "Sanxingdui, located in Guanghan, Southwest China's Sichuan Province, was the capital of the ancient Shu Kingdom and is one of the most significant archaeological discoveries of the 20th century.",
    videoUrl: 'https://example.com/video.mp4',
  }
];
