
export interface Townsquare {
    name: string;
    slug: string;
    description: string;
    image: string;
    dataAiHint: string;
    historicalHandles?: string[];
    nativeWordmark?: string;
}

export interface CountryGroup {
    countryName: string;
    squares: Townsquare[];
}

export const townsquares: Townsquare[] = [
    {
        name: 'Aethelgard',
        slug: 'aethelgard',
        description: 'A world of swords, sorcery, and summoned heroes.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'fantasy castle landscape',
        historicalHandles: ['isekai-hero-kaito', 'demon-lord-valerius', 'alchemist-lina'],
        nativeWordmark: 'Æthelgard',
    },
    {
        name: 'Willingdon',
        slug: 'willingdon',
        description: 'A quiet English town neighboring a rather revolutionary farm.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'english countryside village',
        historicalHandles: ['squealer', 'napoleon', 'snowball', 'mr-jones', 'mr-pilkington', 'mr-frederick', 'mr-whymper'],
    },
    {
        name: 'Istanbul',
        slug: 'istanbul',
        description: 'A bridge between continents, where history meets modernity.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'istanbul cityscape bosphorus',
        historicalHandles: ['ahmed-riza-bey', 'amelie-dubois', 'hafiz-efendi', 'zuhtu-pasazade', 'vicomte-de-valmont', 'hasan-yilmaz', 'elif-aydin', 'ayse-hanim', 'captain-miller', 'halide-edib', 'y-sadri', 't-akar', 's-ozturk', 'l-onur', 'm-aksoy', 't-soray'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Moscow',
        slug: 'moscow',
        description: 'A city of grand history and political power.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'moscow kremlin',
        historicalHandles: ['tsar-nicholas-ii', 'vladimir-lenin', 'russian-peasant', 'pyotr-tchaikovsky'],
        nativeWordmark: 'Городская площадь',
    },
    {
        name: 'St. Petersburg',
        slug: 'st-petersburg',
        description: "Russia's window to Europe, a city of palaces and revolutions.",
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'st petersburg winter palace',
        historicalHandles: ['pierre-bezukhov', 'natasha-rostova', 'andrei-bolkonsky', 'tsar-nicholas-ii', 'vladimir-lenin', 'russian-peasant'],
        nativeWordmark: 'Городская площадь',
    },
     {
        name: 'Tokyo',
        slug: 'tokyo',
        description: 'A dazzling metropolis where tradition and future collide.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'tokyo street crossing',
        historicalHandles: ['kenji-tanaka', 'yuki-sato', 'haruto-ito', 'kenji-t-showa', 'yumi-s-showa', 'haruto-i-showa'],
        nativeWordmark: 'タウンスクエア',
    },
    {
        name: 'Berlin',
        slug: 'berlin',
        description: 'A city reborn, bearing the scars and stories of history.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'berlin brandenburg gate',
        historicalHandles: ['klaus-richter', 'anne-frank', 'eleanor-roosevelt', 'winston-churchill', 'hasan-yilmaz', 'elif-aydin', 'ingrid-schmidt'],
        nativeWordmark: 'Stadtplatz',
    },
    {
        name: 'Copenhagen',
        slug: 'copenhagen',
        description: 'A city of Vikings, sagas, and fairy tales.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'copenhagen harbor houses',
        historicalHandles: ['hrothgar', 'beowulf', 'grendel', 'grendels_mom', 'unferth'],
        nativeWordmark: 'Torvet',
    },
    {
        name: 'Silicon Valley',
        slug: 'silicon-valley',
        description: 'The digital frontier of innovation and technology.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'futuristic cityscape',
    },
    {
        name: 'Kyoto',
        slug: 'kyoto',
        description: 'A serene space where tradition meets tranquility.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'japanese temple garden',
        historicalHandles: ['yuki-sato', 'yumi-s-showa', 'haruto-i-showa'],
        nativeWordmark: 'タウンスクエア',
    },
    {
        name: 'Paris',
        slug: 'paris',
        description: 'The heart of art, culture, and intellectual conversations.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'paris cafe scene',
        historicalHandles: ['ahmed-riza-bey', 'amelie-dubois', 'dario-moreno', 'vicomte-de-valmont'],
        nativeWordmark: 'Place de la Ville',
    },
    {
        name: 'Cairo',
        slug: 'cairo',
        description: 'A bustling marketplace of ideas, history, and trade.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'egyptian market bazaar',
        historicalHandles: ['khaled-am', 'fatima-z'],
        nativeWordmark: 'ميدان المدينة',
    },
    {
        name: 'Rio de Janeiro',
        slug: 'rio-de-janeiro',
        description: 'A vibrant celebration of music, life, and community.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'carnival festival',
        historicalHandles: ['marco-r', 'isabela-c'],
        nativeWordmark: 'Praça da Cidade',
    },
    {
        name: 'Ankara',
        slug: 'ankara',
        description: 'The heart of a republic, a city of history and governance.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'ankara cityscape mausoleum',
        historicalHandles: ['mustafa-kemal', 'ali-usta', 'asker-mehmet', 'zeynep-hanim', 'gazeteci-orhan', 'bulent-ecevit'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'İzmir',
        slug: 'izmir',
        description: 'Pearl of the Aegean, a city of sun, sea, and history.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'izmir clock tower',
        historicalHandles: ['eleni-pappas', 'gen-hacianestis', 'dario-moreno'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Çanakkale',
        slug: 'canakkale',
        description: 'Guardian of the Dardanelles, a city of legends and sacrifice.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'gallipoli peninsula',
        historicalHandles: ['onbasi-halil'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Louisiana',
        slug: 'louisiana',
        description: 'A melting pot of cultures, music, and cuisine.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'new orleans street',
        historicalHandles: ['lou-devereaux'],
    },
    {
        name: 'Austin',
        slug: 'austin',
        description: 'The live music capital of the world.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'live music concert',
        historicalHandles: ['clyde-b', 'jed-jones', 'ethnomusicologist-finch'],
    },
    {
        name: 'Nashville',
        slug: 'nashville',
        description: 'The heart of country music.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'country music guitar',
        historicalHandles: ['helen-parker', 'patty-oconnor', 'fiddlin-jeb', 'ethnomusicologist-finch'],
    },
    {
        name: 'Broadway',
        slug: 'broadway',
        description: 'The grand stage of American theater.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'theater stage curtains',
        historicalHandles: ['leo-rothman'],
    },
    {
        name: 'Hollywood',
        slug: 'hollywood',
        description: 'The dream factory of the film industry.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'hollywood sign',
        historicalHandles: ['eleanor-may'],
    },
    {
        name: 'Rome',
        slug: 'rome',
        description: 'The eternal city of history and empire.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'roman colosseum',
        historicalHandles: ['giacomo-matteotti', 'antonio-gramsci', 'niccolo-paganini', 'padre-lorenzo'],
        nativeWordmark: 'Piazza della Città',
    },
    {
        name: 'Cremona',
        slug: 'cremona',
        description: 'A city of music, violins, and rising political fervor.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'italian city square',
        historicalHandles: ['roberto-farinacci', 'antonio-stradivari', 'niccolo-paganini'],
        nativeWordmark: 'Piazza del Comune',
    },
    {
        name: 'Soho',
        slug: 'soho',
        description: 'A vibrant hub of fashion, art, and nightlife.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'soho street london',
    },
    {
        name: 'New Delhi',
        slug: 'new-delhi',
        description: 'A sprawling city of ancient history and modern dynamism.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'india gate monument',
        historicalHandles: ['asha-s', 'vikram-s'],
        nativeWordmark: 'टाउन स्क्वायर',
    },
    {
        name: 'New York City',
        slug: 'new-york-city',
        description: 'The city that never sleeps, a global financial and cultural center.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'new york skyline',
        historicalHandles: ['frank-connolly'],
    },
    {
        name: 'Washington DC',
        slug: 'washington-dc',
        description: 'The political heart of the United States.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'us capitol building',
        historicalHandles: ['walter-cronkite'],
    },
    {
        name: 'Vienna',
        slug: 'vienna',
        description: 'A city of imperial palaces, classical music, and coffee houses.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'vienna opera house',
        nativeWordmark: 'Stadtplatz',
    },
    {
        name: 'Zurich',
        slug: 'zurich',
        description: 'A global center for banking and finance, nestled by a pristine lake.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'zurich city lake',
        historicalHandles: ['tim-b', 'nicola-p', 'jurgen-s'],
        nativeWordmark: 'Stadtplatz',
    },
    {
        name: 'London',
        slug: 'london',
        description: 'A historic capital grappling with the dawn of a new media age.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'london street vintage',
        historicalHandles: ['arthur-p', 'eleanor-v', 'sid-cooper'],
    },
    {
        name: 'Nicosia/Lefkoşa',
        slug: 'nicosia',
        description: 'The world\'s last divided capital, a city of two stories.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'nicosia city street',
        historicalHandles: ['mehmet-aydin', 'sgt-price-uk'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Famagusta/Mağusa',
        slug: 'famagusta',
        description: 'A port city of deep history and haunting beauty.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'famagusta ghost town',
        historicalHandles: ['eleni-georgiou'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Hatay',
        slug: 'hatay',
        description: 'A land of ancient heritage and a pivotal moment in modern history.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'hatay city view',
        historicalHandles: ['tayfur-sokmen', 'adile-halide', 'jean-gauthier', 'asker-mehmet', 'gazeteci-orhan'],
        nativeWordmark: 'Kasaba Meydanı',
    },
    {
        name: 'Salzburg',
        slug: 'salzburg',
        description: 'The birthplace of Mozart and a stage for the world\'s music.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'salzburg austria skyline',
        historicalHandles: ['w-a-mozart'],
        nativeWordmark: 'Stadtplatz'
    },
    {
        name: 'Bonn',
        slug: 'bonn',
        description: 'A historic German city on the Rhine, birthplace of Beethoven.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'bonn germany rhine river',
        historicalHandles: ['ludwig-v-beethoven'],
        nativeWordmark: 'Stadtplatz'
    },
    {
        name: 'La Mancha',
        slug: 'la-mancha',
        description: 'A sun-drenched plain of windmills and chivalrous dreams.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'spain windmills landscape',
        historicalHandles: ['don-quixote-mancha', 'sancho-panza'],
        nativeWordmark: 'Plaza del Pueblo',
    },
    {
        name: 'Sierra Morena',
        slug: 'sierra-morena',
        description: 'A rugged mountain range, a refuge for penitents and madmen.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'spain mountain range',
        historicalHandles: ['don-quixote-mancha', 'sancho-panza'],
        nativeWordmark: 'Plaza del Pueblo',
    },
    {
        name: 'El Toboso',
        slug: 'el-toboso',
        description: 'A humble village, home to the peerless lady of a knight\'s heart.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'spanish village whitewashed',
        historicalHandles: ['don-quixote-mancha', 'sancho-panza'],
        nativeWordmark: 'Plaza del Pueblo',
    },
    {
        name: 'Barcelona',
        slug: 'barcelona',
        description: 'A vibrant coastal city of printing presses and enchanted galleys.',
        image: 'https://placehold.co/400x400.png',
        dataAiHint: 'barcelona gothic quarter',
        historicalHandles: ['don-quixote-mancha', 'sancho-panza'],
        nativeWordmark: 'Plaça de la Vila',
    },
];

export const townsquaresByCountry: CountryGroup[] = [
    {
        countryName: 'Türkiye',
        squares: townsquares.filter(ts => ['istanbul', 'ankara', 'izmir', 'canakkale', 'hatay'].includes(ts.slug)),
    },
    {
        countryName: 'KKTC / Northern Cyprus',
        squares: townsquares.filter(ts => ['nicosia', 'famagusta'].includes(ts.slug)),
    },
    {
        countryName: 'United States',
        squares: townsquares.filter(ts => ['new-york-city', 'washington-dc', 'hollywood', 'broadway', 'louisiana', 'austin', 'nashville', 'silicon-valley'].includes(ts.slug)),
    },
    {
        countryName: 'United Kingdom',
        squares: townsquares.filter(ts => ['soho', 'london', 'willingdon'].includes(ts.slug)),
    },
    {
        countryName: 'Germany',
        squares: townsquares.filter(ts => ['berlin', 'bonn'].includes(ts.slug)),
    },
    {
        countryName: 'Russia',
        squares: townsquares.filter(ts => ['moscow', 'st-petersburg'].includes(ts.slug)),
    },
    {
        countryName: 'Japan',
        squares: townsquares.filter(ts => ['tokyo', 'kyoto'].includes(ts.slug)),
    },
    {
        countryName: 'Denmark',
        squares: townsquares.filter(ts => ['copenhagen'].includes(ts.slug)),
    },
    {
        countryName: 'France',
        squares: townsquares.filter(ts => ['paris'].includes(ts.slug)),
    },
     {
        countryName: 'Switzerland',
        squares: townsquares.filter(ts => ['zurich'].includes(ts.slug)),
    },
    {
        countryName: 'Egypt',
        squares: townsquares.filter(ts => ['cairo'].includes(ts.slug)),
    },
    {
        countryName: 'Brazil',
        squares: townsquares.filter(ts => ['rio-de-janeiro'].includes(ts.slug)),
    },
    {
        countryName: 'Italy',
        squares: townsquares.filter(ts => ['rome', 'cremona'].includes(ts.slug)),
    },
    {
        countryName: 'India',
        squares: townsquares.filter(ts => ['new-delhi'].includes(ts.slug)),
    },
    {
        countryName: 'Austria',
        squares: townsquares.filter(ts => ['vienna', 'salzburg'].includes(ts.slug)),
    },
    {
        countryName: 'Spain (Fictional)',
        squares: townsquares.filter(ts => ['la-mancha', 'sierra-morena', 'el-toboso', 'barcelona'].includes(ts.slug)),
    },
    {
        countryName: 'Fictional',
        squares: townsquares.filter(ts => ['aethelgard', 'willingdon', 'la-mancha', 'sierra-morena', 'el-toboso', 'barcelona'].includes(ts.slug)),
    }
];
