
'use client';

export {
    Home,
    Cog,
    Search,
    MoreHorizontal,
    Compass,
    Library,
    PlusCircle,
    FileText,
    Video,
    Rss,
    Mic,
    Shield,
    ImageIcon,
    Clapperboard,
    Heart,
    PenTool,
    Flame,
    HeartPulse,
    Globe,
    BookMarked,
    BookCopy,
    Book,
    BookCheck,
    Voicemail,
    LogOut,
    Swords,
    Music,
    Ticket,
    Tractor,
    Luggage,
    Palmtree,
    Grid,
    MessageSquareQuote,
    Link as LinkIcon,
    AlertTriangle,
    Gamepad2,
    Utensils,
    ArrowLeft,
    Settings,
    Newspaper,
    Users,
    MessageSquare,
    Briefcase,
    UserCircle,
    Landmark,
    BarChart3,
    CheckCircle,
    UserCircle2,
    KeyRound,
    ShieldCheck,
    ShieldAlert,
    Ban,
    Trash2,
    Code,
    User,
    Eye,
    Palette,
    Bell,
    BrainCircuit,
    Hand,
    Download,
    FileLock2,
    Wallet,
    Beaker,
    Smartphone,
    Upload,
    Flag,
    Phone,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    Bot,
    UploadCloud,
    ArrowRight,
    PlayCircle,
    MapPin,
    Car,
    ShoppingCart,
    Play,
    Pause,
    RotateCw,
    Wind,
    Sun,
    Moon,
    Pencil,
    Eraser,
    Calculator,
    Disc3,
    Mail,
    CalculatorIcon,
    Footprints,
    BedDouble,
    SunMedium,
    CloudSun,
    Cloud,
    CloudRain,
    Tornado,
    Waves,
    Siren,
    ThermometerSun,
    Info,
    List,
    ThumbsUp,
    ThumbsDown,
    Share,
    Bookmark,
    ChevronDown,
    ChevronRight,
    X,
    Repeat,
    ListMusic,
    Shuffle,
    SkipBack,
    SkipForward,
    Rewind,
    FastForward,
    ListOrdered,
    Italic,
    Underline,
    Bold,
    Calendar,
    Sparkles,
    ChefHat,
    SendHorizonal,
    Paperclip,
    ArrowUpDown,
    ListFilter,
    Layers,
    Navigation,
    LocateFixed,
    Star,
    Undo,
    AlignLeft,
    Square,
    Power,
    Map,
    BookOpen,
    Loader2,
    Terminal,
    Club,
    Diamond,
    Spade,
    Stamp,
    Send,
    PencilLine,
    Share2,
    Shapes,
    Pen,
} from 'lucide-react';

export const Postcard = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <rect width="18" height="12" x="3" y="6" rx="2" ry="2" />
        <line x1="3" x2="21" y1="12" y2="12" />
        <line x1="13" x2="13" y1="6" y2="12" />
    </svg>
);

export const Bugle = (props: React.SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
    <path d="M16.5 16.5a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
    <path d="M16.5 14H6a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h1"/>
    <path d="M7 4V2"/>
    <path d="M10 4V2"/>
  </svg>
);

export const Megaphone = (props: React.SVGProps<SVGSVGElement>) => (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
        <path d="m3 11 18-5v12L3 14v-3z"/>
        <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6"/>
    </svg>
);
